# Nombre de la aplicación
spring.application.name=appLiteratura

# Configuración de la base de datos
spring.datasource.url=${BASE_URL}
spring.datasource.username=${BASE_NAME}
spring.datasource.password=${BASE_PASSWORD}

# Driver de PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración JPA (Hibernate)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#configuracion de logger - PARA ERRORES
logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=INFO